#datasources
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board-saturday?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: cos1234