#datasources
spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        use_sql_comments: true #JPQL을 코멘트로 앞에 보여주기
    show-sql: true
    output:
      ansi:
        enabled: always


logging:
  level:
    com.jyujyu.dayonetest: DEBUG
    org.hibernate.type: TRACE